import dash
from dash import html
import feffery_antd_components as fac

app = dash.Dash(__name__)

components = [
    'AntdButton',
    'AntdFloatButton',
    'AntdFloatButtonGroup',
    'AntdIcon',
    'AntdParagraph',
    'AntdText',
    'AntdTitle',
    'AntdCenter',
    'AntdDivider',
    'AntdFlex',
    'AntdRow',
    'AntdCol',
    'AntdSpace',
    'AntdCompact',
    'AntdLayout',
    'AntdHeader',
    'AntdContent',
    'AntdFooter',
    'AntdSider',
    'AntdAnchor',
    'AntdBreadcrumb',
    'AntdDropdown',
    'AntdMenu',
    'AntdPageHeader',
    'AntdPagination',
    'AntdSteps',
    'AntdEditorLayout',
    'AntdDraggablePanel',
    'AntdAffix',
    'AntdBackTop',
    'AntdConfigProvider',
    'Fragment',
    'AntdAlert',
    'AntdDrawer',
    'AntdMessage',
    'AntdModal',
    'AntdNotification',
    'AntdPopconfirm',
    'AntdPopupCard',
    'AntdProgress',
    'AntdResult',
    'AntdCustomSkeleton',
    'AntdSkeletonAvatar',
    'AntdSkeletonButton',
    'AntdSkeletonImage',
    'AntdSkeleton',
    'AntdSpin',
    'AntdAccordion',
    'AntdAvatar',
    'AntdAvatarGroup',
    'AntdBadge',
    'AntdCardGrid',
    'AntdCardMeta',
    'AntdCard',
    'AntdCarousel',
    'AntdCheckableTag',
    'AntdCollapse',
    'AntdComment',
    'AntdDescriptions',
    'AntdDescriptionItem',
    'AntdEmpty',
    'AntdImage',
    'AntdImageGroup',
    'AntdPopover',
    'AntdQRCode',
    'AntdRibbon',
    'AntdSegmented',
    'AntdSpoiler',
    'AntdStatistic',
    'AntdCountdown',
    'AntdTable',
    'AntdTabs',
    'AntdTag',
    'AntdTimeline',
    'AntdTooltip',
    'AntdTree',
    'AntdCalendar',
    'AntdCascader',
    'AntdCheckbox',
    'AntdCheckboxGroup',
    'AntdCheckCard',
    'AntdCheckCardGroup',
    'AntdColorPicker',
    'AntdDatePicker',
    'AntdDateRangePicker',
    'AntdForm',
    'AntdFormItem',
    'AntdInput',
    'AntdOTP',
    'AntdInputNumber',
    'AntdMentions',
    'AntdRadioGroup',
    'AntdRate',
    'AntdSegmentedColoring',
    'AntdSelect',
    'AntdSlider',
    'AntdSwitch',
    'AntdTimePicker',
    'AntdTimeRangePicker',
    'AntdTransfer',
    'AntdTreeSelect',
    'AntdPictureUpload',
    'AntdDraggerUpload',
    'AntdUpload',
    'AntdWatermark',
    'AntdTour',
    'AntdCopyText',
]

app.layout = html.Div(
    [
        fac.AntdTabs(
            items=[
                {
                    'label': component,
                    'key': component,
                    'children': html.Pre(
                        getattr(fac, component).__doc__,
                        style={
                            'maxHeight': 'calc(100vh - 200px)',
                            'overflowY': 'auto',
                        },
                    ),
                }
                for component in components[::-1]
            ],
            activeKey=components[-1],
        )
    ],
    style={'padding': 30},
)

if __name__ == '__main__':
    app.run(debug=True)
