import {
    ToolTwoTone,
    NotificationTwoTone,
    HourglassTwoTone,
    CloudTwoTone,
    ApiTwoTone,
    SlidersTwoTone,
    FundTwoTone,
    BoxPlotTwoTone,
    PieChartTwoTone,
    HighlightTwoTone,
    DeleteTwoTone,
    EditTwoTone,
    CheckSquareTwoTone,
    CheckCircleTwoTone,
    CloseSquareTwoTone,
    CloseCircleTwoTone,
    ExclamationCircleTwoTone,
    InfoCircleTwoTone,
    MinusSquareTwoTone,
    PlusSquareTwoTone,
    MinusCircleTwoTone,
    PlusCircleTwoTone,
    QuestionCircleTwoTone,
    RightSquareTwoTone,
    LeftSquareTwoTone,
    DownSquareTwoTone,
    UpSquareTwoTone,
    DownCircleTwoTone,
    UpCircleTwoTone,
    RightCircleTwoTone,
    LeftCircleTwoTone,
    StarOutlined,
    SkinOutlined,
    SmileOutlined,
    InsuranceOutlined,
    BlockOutlined,
    BankOutlined,
    SketchOutlined,
    CheckOutlined,
    CloseOutlined,
    MinusOutlined,
    PlusOutlined,
    QuestionOutlined,
    FullscreenOutlined,
    DownOutlined,
    UpOutlined,
    LeftOutlined,
    RightOutlined,
    ArrowDownOutlined,
    ArrowUpOutlined,
    ArrowLeftOutlined,
    ArrowRightOutlined,
    ManOutlined,
    WomanOutlined,
    UserDeleteOutlined,
    UserAddOutlined,
    TrophyOutlined,
    SelectOutlined,
    ThunderboltOutlined,
    TagsOutlined,
    TagOutlined,
    SoundOutlined,
    ShoppingCartOutlined,
    RobotOutlined,
    PushpinOutlined,
    PrinterOutlined,
    PictureOutlined,
    PhoneOutlined,
    PartitionOutlined,
    MoreOutlined,
    MonitorOutlined,
    MoneyCollectOutlined,
    MobileOutlined,
    LinkOutlined,
    LayoutOutlined,
    IdcardOutlined,
    GiftOutlined,
    FunnelPlotOutlined,
    FundProjectionScreenOutlined,
    ForkOutlined,
    FolderOpenOutlined,
    FolderOutlined,
    FolderAddOutlined,
    FlagOutlined,
    FireOutlined,
    FilterOutlined,
    FileZipOutlined,
    FileWordOutlined,
    FileTextOutlined,
    FileSyncOutlined,
    FileProtectOutlined,
    FilePdfOutlined,
    FileMarkdownOutlined,
    FileImageOutlined,
    FileOutlined,
    FileDoneOutlined,
    FileAddOutlined,
    FieldTimeOutlined,
    FieldStringOutlined,
    FieldNumberOutlined,
    FieldBinaryOutlined,
    EyeInvisibleOutlined,
    EyeOutlined,
    ExperimentOutlined,
    ExceptionOutlined,
    EnvironmentOutlined,
    DownloadOutlined,
    DollarOutlined,
    EuroOutlined,
    LikeOutlined,
    DislikeOutlined,
    DisconnectOutlined,
    DesktopOutlined,
    DeploymentUnitOutlined,
    CrownOutlined,
    CoffeeOutlined,
    CloudSyncOutlined,
    CarryOutOutlined,
    CarOutlined,
    BulbOutlined,
    BuildOutlined,
    BugOutlined,
    BranchesOutlined,
    BarcodeOutlined,
    AimOutlined,
    IssuesCloseOutlined,
    EllipsisOutlined,
    HomeOutlined,
    FundOutlined,
    RadarChartOutlined,
    BarChartOutlined,
    PieChartOutlined,
    DotChartOutlined,
    LineChartOutlined,
    ApartmentOutlined,
    AppstoreOutlined,
    AppstoreAddOutlined,
    BellOutlined,
    CalculatorOutlined,
    DatabaseOutlined,
    CalendarOutlined,
    HistoryOutlined,
    SearchOutlined,
    FileSearchOutlined,
    CloudDownloadOutlined,
    CloudServerOutlined,
    CloudUploadOutlined,
    SwapOutlined,
    RollbackOutlined,
    LoginOutlined,
    TableOutlined,
    LogoutOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    FullscreenExitOutlined,
    QuestionCircleOutlined,
    PlusCircleOutlined,
    MinusCircleOutlined,
    InfoCircleOutlined,
    ExclamationCircleOutlined,
    CloseCircleOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    StopOutlined,
    EditOutlined,
    DeleteOutlined,
    HighlightOutlined,
    RedoOutlined,
    UndoOutlined,
    ZoomInOutlined,
    ZoomOutOutlined,
    SortAscendingOutlined,
    SortDescendingOutlined,
    AreaChartOutlined,
    BoxPlotOutlined,
    FallOutlined,
    RiseOutlined,
    StockOutlined,
    GithubOutlined,
    WeiboCircleOutlined,
    AlipayOutlined,
    AlipayCircleOutlined,
    AccountBookOutlined,
    AlertOutlined,
    ApiOutlined,
    BarsOutlined,
    BookOutlined,
    CameraOutlined,
    ClearOutlined,
    CloudOutlined,
    ClusterOutlined,
    CodeOutlined,
    CommentOutlined,
    CompassOutlined,
    ConsoleSqlOutlined,
    ControlOutlined,
    DashboardOutlined,
    ExportOutlined,
    ImportOutlined,
    FunctionOutlined,
    GlobalOutlined,
    HourglassOutlined,
    KeyOutlined,
    LoadingOutlined,
    LockOutlined,
    MailOutlined,
    MenuOutlined,
    NotificationOutlined,
    NumberOutlined,
    PoweroffOutlined,
    QrcodeOutlined,
    ReadOutlined,
    ReloadOutlined,
    SaveOutlined,
    RocketOutlined,
    ScheduleOutlined,
    SendOutlined,
    SettingOutlined,
    SyncOutlined,
    TeamOutlined,
    ToolOutlined,
    UnlockOutlined,
    UserOutlined,
    CaretUpOutlined,
    CaretDownOutlined,
    CaretLeftOutlined,
    CaretRightOutlined,
    UpCircleOutlined,
    DownCircleOutlined,
    LeftCircleOutlined,
    RightCircleOutlined,
    EnterOutlined,
    RetweetOutlined,
    WarningOutlined,
    FormOutlined,
    CopyOutlined,
    ScissorOutlined,
    SnippetsOutlined,
    DiffOutlined,
    OrderedListOutlined,
    UnorderedListOutlined,
    SlidersOutlined,
    AuditOutlined,
    BorderOutlined,
    ContactsOutlined,
    ContainerOutlined,
    DeliveredProcedureOutlined,
    PauseOutlined,
    StepBackwardOutlined,
    StepForwardOutlined,
    FastForwardOutlined,
    FastBackwardOutlined
} from '@ant-design/icons';
import {
    BsAlarm,
    BsEnvelope,
    BsEnvelopeOpen,
    BsLink,
    BsLink45Deg,
    BsListCheck,
    BsListTask
} from "react-icons/bs/index.esm";
import {
    BiAnalyse,
    BiTable,
    BiLayer,
    BiLayerMinus,
    BiLayerPlus
} from "react-icons/bi/index.esm";
import {
    DiPython,
    DiLinux,
    DiChrome,
    DiDatabase,
    DiFirefox,
    DiMarkdown,
    DiPostgresql,
    DiTerminal,
    DiWindows
} from "react-icons/di/index.esm";
import {
    FcAdvertising,
    FcApproval,
    FcBookmark,
    FcBearish,
    FcBullish,
    FcCalculator,
    FcCalendar,
    FcCommandLine,
    FcDataSheet,
    FcElectronics,
    FcFolder,
    FcGlobe,
    FcInspection,
    FcOk,
    FcOpenedFolder,
    FcOrgUnit,
    FcParallelTasks,
    FcPlanner,
    FcNegativeDynamic,
    FcPositiveDynamic,
    FcSafe,
    FcSerialTasks,
    FcSearch,
    FcStatistics,
    FcSupport,
    FcSynchronize,
    FcTodoList,
    FcWorkflow,
    FcComboChart,
    FcAreaChart,
    FcBarChart,
    FcDoughnutChart,
    FcFlowChart,
    FcLineChart,
    FcPieChart,
    FcScatterPlot,
    FcRadarPlot,
    FcAbout,
    FcAcceptDatabase,
    FcAddDatabase,
    FcAlphabeticalSortingAz,
    FcAlphabeticalSortingZa,
    FcAutomatic,
    FcBinoculars,
    FcBriefcase,
    FcCancel,
    FcCheckmark,
    FcDataBackup,
    FcDataConfiguration,
    FcDataEncryption,
    FcConferenceCall,
    FcDataProtection,
    FcDatabase,
    FcDeleteDatabase,
    FcDeployment,
    FcDocument,
    FcDownload,
    FcEmptyTrash,
    FcExport,
    FcFaq,
    FcFile,
    FcFinePrint,
    FcFullTrash,
    FcGenealogy,
    FcHighPriority,
    FcHome,
    FcIdea,
    FcImageFile,
    FcImport,
    FcInfo,
    FcLikePlaceholder,
    FcLike,
    FcList,
    FcLowPriority,
    FcMenu,
    FcMindMap,
    FcMultipleInputs,
    FcNumericalSorting12,
    FcNumericalSorting21,
    FcOrganization,
    FcOvertime,
    FcPlus,
    FcProcess,
    FcQuestions,
    FcRules,
    FcServices,
    FcSettings,
    FcShare,
    FcSignature,
    FcSurvey,
    FcTemplate,
    FcTimeline,
    FcTreeStructure,
    FcUpload,
    FcViewDetails,
    FcVlc
} from "react-icons/fc/index.esm";
import {
    MdAccountCircle,
    MdAlarm,
    MdAlarmAdd,
    MdAlarmOff,
    MdAlarmOn,
    MdAssessment,
    MdAssignment,
    MdBugReport,
    MdBuild,
    MdCode,
    MdDashboard,
    MdDelete,
    MdDeleteForever,
    MdDescription,
    MdEvent,
    MdExitToApp,
    MdExplore,
    MdExtension,
    MdFavorite,
    MdFavoriteBorder,
    MdFindInPage,
    MdFingerprint,
    MdGTranslate,
    MdGetApp,
    MdHelp,
    MdHelpOutline,
    MdHighlightOff,
    MdHistory,
    MdHome,
    MdHourglassEmpty,
    MdInfo,
    MdInfoOutline,
    MdInput,
    MdLabel,
    MdLabelOutline,
    MdLaunch,
    MdLightbulbOutline,
    MdList,
    MdLockOpen,
    MdLockOutline,
    MdNoteAdd,
    MdOpacity,
    MdPowerSettingsNew,
    MdQueryBuilder,
    MdRestore,
    MdSchedule,
    MdSearch,
    MdSettings,
    MdSubject,
    MdSupervisorAccount,
    MdSwapHoriz,
    MdSwapVert,
    MdThumbDown,
    MdThumbUp,
    MdTimeline,
    MdToc,
    MdTranslate,
    MdTrendingDown,
    MdTrendingFlat,
    MdTrendingUp,
    MdUpdate,
    MdVerifiedUser,
    MdVisibility,
    MdVisibilityOff,
    MdAddAlert,
    MdEqualizer,
    MdLibraryAdd,
    MdLibraryBooks,
    MdNotInterested,
    MdEmail,
    MdMailOutline,
    MdLocationOn,
    MdAddCircle,
    MdAddCircleOutline,
    MdAdd,
    MdAddBox,
    MdBackspace,
    MdBlock,
    MdClear,
    MdContentCopy,
    MdContentCut,
    MdContentPaste,
    MdCreate,
    MdDrafts,
    MdFlag,
    MdForward,
    MdGesture,
    MdLink,
    MdLowPriority,
    MdRemove,
    MdRemoveCircle,
    MdRemoveCircleOutline,
    MdSave,
    MdStorage,
    MdAttachFile,
    MdFormatQuote,
    MdFunctions,
    MdInsertChart,
    MdCloudDone,
    MdCloudDownload,
    MdCloudQueue,
    MdCloudUpload,
    MdCreateNewFolder,
    MdFileDownload,
    MdFileUpload,
    MdTimer,
    MdTimerOff,
    MdTransform,
    MdTune,
    MdEditLocation,
    MdLayers,
    MdLayersClear,
    MdPinDrop,
    MdNotifications,
    MdPlusOne,
    MdPeople,
    MdStar,
    MdStarBorder,
    MdStarHalf
} from "react-icons/md/index.esm";
import {
    ImEarth,
    ImSphere
} from "react-icons/im/index.esm";
import { GiMeshNetwork } from "react-icons/gi/index.esm";
import {
    PiCircle,
    PiPolygon,
    PiMapPin,
    PiLineSegment,
    PiLineSegments,
    PiTrashSimple,
    PiTrash,
    PiRuler,
    PiSelection,
    PiSelectionSlash,
    PiSquareSplitHorizontal,
    PiSquareSplitVertical,
    PiStackSimple,
    PiStack,
    PiNavigationArrow,
    PiMapTrifold,
    PiInfo,
    PiLockKeyOpen,
    PiLockKey,
    PiGear,
    PiAirplane,
    PiAnchorSimple,
    PiArrowArcLeft,
    PiArrowArcRight,
    PiArrowClockwise,
    PiArrowCounterClockwise,
    PiBarricade,
    PiBinoculars,
    PiBoundingBox,
    PiBroom,
    PiBuildings,
    PiCalculator,
    PiCamera,
    PiCircuitry,
    PiClipboard,
    PiCompass,
    PiCopy,
    PiCpu,
    PiCrosshair,
    PiCubeFocus,
    PiCube,
    PiCursor,
    PiDatabase,
    PiEyeSlash,
    PiEye,
    PiFaders,
    PiFloppyDisk,
    PiDotsThreeVertical,
    PiDotsThree,
    PiMathOperations,
    PiPlus,
    PiMinus,
    PiPath
} from 'react-icons/pi/index.esm';
import { SiGitee } from 'react-icons/si/index.esm'

// vscode中，使用正则查找目标后，按快捷键alt+enter批量选中匹配项
const str2Icon = new Map([
    ['antd-carry-out', <CarryOutOutlined />],
    ['antd-car', <CarOutlined />],
    ['antd-bulb', <BulbOutlined />],
    ['antd-build', <BuildOutlined />],
    ['antd-bug', <BugOutlined />],
    ['antd-bar-code', <BarcodeOutlined />],
    ['antd-branches', <BranchesOutlined />],
    ['antd-aim', <AimOutlined />],
    ['antd-issues-close', <IssuesCloseOutlined />],
    ['antd-ellipsis', <EllipsisOutlined />],
    ['antd-user', <UserOutlined />],
    ['antd-unlock', <UnlockOutlined />],
    ['antd-repair', <ToolOutlined />],
    ['antd-team', <TeamOutlined />],
    ['antd-sync', <SyncOutlined />],
    ['antd-setting', <SettingOutlined />],
    ['antd-send', <SendOutlined />],
    ['antd-schedule', <ScheduleOutlined />],
    ['antd-save', <SaveOutlined />],
    ['antd-rocket', <RocketOutlined />],
    ['antd-reload', <ReloadOutlined />],
    ['antd-read', <ReadOutlined />],
    ['antd-qrcode', <QrcodeOutlined />],
    ['antd-power-off', <PoweroffOutlined />],
    ['antd-number', <NumberOutlined />],
    ['antd-notification', <NotificationOutlined />],
    ['antd-menu', <MenuOutlined />],
    ['antd-mail', <MailOutlined />],
    ['antd-lock', <LockOutlined />],
    ['antd-loading', <LoadingOutlined />],
    ['antd-key', <KeyOutlined />],
    ['antd-hourglass', <HourglassOutlined />],
    ['antd-global', <GlobalOutlined />],
    ['antd-function', <FunctionOutlined />],
    ['antd-import', <ImportOutlined />],
    ['antd-export', <ExportOutlined />],
    ['antd-dashboard', <DashboardOutlined />],
    ['antd-control', <ControlOutlined />],
    ['antd-console-sql', <ConsoleSqlOutlined />],
    ['antd-compass', <CompassOutlined />],
    ['antd-comment', <CommentOutlined />],
    ['antd-code', <CodeOutlined />],
    ['antd-cluster', <ClusterOutlined />],
    ['antd-clear', <ClearOutlined />],
    ['antd-camera', <CameraOutlined />],
    ['antd-book', <BookOutlined />],
    ['antd-catalog', <BarsOutlined />],
    ['antd-api', <ApiOutlined />],
    ['antd-alert', <AlertOutlined />],
    ['antd-account-book', <AccountBookOutlined />],
    ['antd-alipay', <AlipayOutlined />],
    ['antd-alipay-circle', <AlipayCircleOutlined />],
    ['antd-weibo', <WeiboCircleOutlined />],
    ['antd-github', <GithubOutlined />],
    ['antd-fall', <FallOutlined />],
    ['antd-rise', <RiseOutlined />],
    ['antd-stock', <StockOutlined />],
    ['antd-home', <HomeOutlined />],
    ['antd-fund', <FundOutlined />],
    ['antd-area-chart', <AreaChartOutlined />],
    ['antd-radar-chart', <RadarChartOutlined />],
    ['antd-bar-chart', <BarChartOutlined />],
    ['antd-pie-chart', <PieChartOutlined />],
    ['antd-box-plot', <BoxPlotOutlined />],
    ['antd-dot-chart', <DotChartOutlined />],
    ['antd-line-chart', <LineChartOutlined />],
    ['antd-field-binary', <FieldBinaryOutlined />],
    ['antd-field-number', <FieldNumberOutlined />],
    ['antd-field-string', <FieldStringOutlined />],
    ['antd-field-time', <FieldTimeOutlined />],
    ['antd-file-add', <FileAddOutlined />],
    ['antd-file-done', <FileDoneOutlined />],
    ['antd-file', <FileOutlined />],
    ['antd-file-image', <FileImageOutlined />],
    ['antd-file-markdown', <FileMarkdownOutlined />],
    ['antd-file-pdf', <FilePdfOutlined />],
    ['antd-file-protect', <FileProtectOutlined />],
    ['antd-file-sync', <FileSyncOutlined />],
    ['antd-file-text', <FileTextOutlined />],
    ['antd-file-word', <FileWordOutlined />],
    ['antd-file-zip', <FileZipOutlined />],
    ['antd-filter', <FilterOutlined />],
    ['antd-fire', <FireOutlined />],
    ['antd-woman', <WomanOutlined />],
    ['antd-arrow-up', <ArrowUpOutlined />],
    ['antd-arrow-down', <ArrowDownOutlined />],
    ['antd-arrow-left', <ArrowLeftOutlined />],
    ['antd-arrow-right', <ArrowRightOutlined />],
    ['antd-flag', <FlagOutlined />],
    ['antd-user-add', <UserAddOutlined />],
    ['antd-folder-add', <FolderAddOutlined />],
    ['antd-man', <ManOutlined />],
    ['antd-tag', <TagOutlined />],
    ['antd-folder', <FolderOutlined />],
    ['antd-user-delete', <UserDeleteOutlined />],
    ['antd-trophy', <TrophyOutlined />],
    ['antd-shopping-cart', <ShoppingCartOutlined />],
    ['antd-folder-open', <FolderOpenOutlined />],
    ['antd-fork', <ForkOutlined />],
    ['antd-select', <SelectOutlined />],
    ['antd-tags', <TagsOutlined />],
    ['antd-thunderbolt', <ThunderboltOutlined />],
    ['antd-sound', <SoundOutlined />],
    ['antd-fund-projection-screen', <FundProjectionScreenOutlined />],
    ['antd-funnel-plot', <FunnelPlotOutlined />],
    ['antd-gift', <GiftOutlined />],
    ['antd-robot', <RobotOutlined />],
    ['antd-pushpin', <PushpinOutlined />],
    ['antd-printer', <PrinterOutlined />],
    ['antd-phone', <PhoneOutlined />],
    ['antd-picture', <PictureOutlined />],
    ['antd-idcard', <IdcardOutlined />],
    ['antd-partition', <PartitionOutlined />],
    ['antd-monitor', <MonitorOutlined />],
    ['antd-more', <MoreOutlined />],
    ['antd-apartment', <ApartmentOutlined />],
    ['antd-money-collect', <MoneyCollectOutlined />],
    ['antd-experiment', <ExperimentOutlined />],
    ['antd-link', <LinkOutlined />],
    ['antd-mobile', <MobileOutlined />],
    ['antd-coffee', <CoffeeOutlined />],
    ['antd-layout', <LayoutOutlined />],
    ['antd-eye', <EyeOutlined />],
    ['antd-eye-invisible', <EyeInvisibleOutlined />],
    ['antd-exception', <ExceptionOutlined />],
    ['antd-dollar', <DollarOutlined />],
    ['antd-euro', <EuroOutlined />],
    ['antd-download', <DownloadOutlined />],
    ['antd-environment', <EnvironmentOutlined />],
    ['antd-deployment-unit', <DeploymentUnitOutlined />],
    ['antd-crown', <CrownOutlined />],
    ['antd-desktop', <DesktopOutlined />],
    ['antd-like', <LikeOutlined />],
    ['antd-dislike', <DislikeOutlined />],
    ['antd-disconnect', <DisconnectOutlined />],
    ['antd-app-store', <AppstoreOutlined />],
    ['antd-app-store-add', <AppstoreAddOutlined />],
    ['antd-bell', <BellOutlined />],
    ['antd-calculator', <CalculatorOutlined />],
    ['antd-calendar', <CalendarOutlined />],
    ['antd-database', <DatabaseOutlined />],
    ['antd-history', <HistoryOutlined />],
    ['antd-search', <SearchOutlined />],
    ['antd-file-search', <FileSearchOutlined />],
    ['antd-cloud', <CloudOutlined />],
    ['antd-cloud-upload', <CloudUploadOutlined />],
    ['antd-cloud-download', <CloudDownloadOutlined />],
    ['antd-cloud-server', <CloudServerOutlined />],
    ['antd-cloud-sync', <CloudSyncOutlined />],
    ['antd-swap', <SwapOutlined />],
    ['antd-rollback', <RollbackOutlined />],
    ['antd-login', <LoginOutlined />],
    ['antd-logout', <LogoutOutlined />],
    ['antd-menu-fold', <MenuFoldOutlined />],
    ['antd-menu-unfold', <MenuUnfoldOutlined />],
    ['antd-full-screen', <FullscreenOutlined />],
    ['antd-full-screen-exit', <FullscreenExitOutlined />],
    ['antd-question-circle', <QuestionCircleOutlined />],
    ['antd-plus-circle', <PlusCircleOutlined />],
    ['antd-minus-circle', <MinusCircleOutlined />],
    ['antd-info-circle', <InfoCircleOutlined />],
    ['antd-exclamation-circle', <ExclamationCircleOutlined />],
    ['antd-close-circle', <CloseCircleOutlined />],
    ['antd-check-circle', <CheckCircleOutlined />],
    ['antd-clock-circle', <ClockCircleOutlined />],
    ['antd-stop', <StopOutlined />],
    ['antd-edit', <EditOutlined />],
    ['antd-delete', <DeleteOutlined />],
    ['antd-highlight', <HighlightOutlined />],
    ['antd-redo', <RedoOutlined />],
    ['antd-undo', <UndoOutlined />],
    ['antd-zoom-in', <ZoomInOutlined />],
    ['antd-zoom-out', <ZoomOutOutlined />],
    ['antd-sort-ascending', <SortAscendingOutlined />],
    ['antd-sort-descending', <SortDescendingOutlined />],
    ['antd-table', <TableOutlined />],
    ['antd-question', <QuestionOutlined />],
    ['antd-plus', <PlusOutlined />],
    ['antd-minus', <MinusOutlined />],
    ['antd-close', <CloseOutlined />],
    ['antd-check', <CheckOutlined />],
    ['antd-sketch', <SketchOutlined />],
    ['antd-bank', <BankOutlined />],
    ['antd-block', <BlockOutlined />],
    ['antd-insurance', <InsuranceOutlined />],
    ['antd-smile', <SmileOutlined />],
    ['antd-skin', <SkinOutlined />],
    ['antd-star', <StarOutlined />],
    ['antd-right-circle-two-tone', <RightCircleTwoTone />],
    ['antd-left-circle-two-tone', <LeftCircleTwoTone />],
    ['antd-up-circle-two-tone', <UpCircleTwoTone />],
    ['antd-down-circle-two-tone', <DownCircleTwoTone />],
    ['antd-up-square-two-tone', <UpSquareTwoTone />],
    ['antd-down-square-two-tone', <DownSquareTwoTone />],
    ['antd-left-square-two-tone', <LeftSquareTwoTone />],
    ['antd-right-square-two-tone', <RightSquareTwoTone />],
    ['antd-question-circle-two-tone', <QuestionCircleTwoTone />],
    ['antd-plus-circle-two-tone', <PlusCircleTwoTone />],
    ['antd-minus-circle-two-tone', <MinusCircleTwoTone />],
    ['antd-plus-square-two-tone', <PlusSquareTwoTone />],
    ['antd-minus-square-two-tone', <MinusSquareTwoTone />],
    ['antd-info-circle-two-tone', <InfoCircleTwoTone />],
    ['antd-exclamation-circle-two-tone', <ExclamationCircleTwoTone />],
    ['antd-close-circle-two-tone', <CloseCircleTwoTone />],
    ['antd-close-square-two-tone', <CloseSquareTwoTone />],
    ['antd-check-circle-two-tone', <CheckCircleTwoTone />],
    ['antd-check-square-two-tone', <CheckSquareTwoTone />],
    ['antd-edit-two-tone', <EditTwoTone />],
    ['antd-delete-two-tone', <DeleteTwoTone />],
    ['antd-highlight-two-tone', <HighlightTwoTone />],
    ['antd-pie-chart-two-tone', <PieChartTwoTone />],
    ['antd-box-chart-two-tone', <BoxPlotTwoTone />],
    ['antd-fund-two-tone', <FundTwoTone />],
    ['antd-sliders-two-tone', <SlidersTwoTone />],
    ['antd-api-two-tone', <ApiTwoTone />],
    ['antd-cloud-two-tone', <CloudTwoTone />],
    ['antd-hourglass-two-tone', <HourglassTwoTone />],
    ['antd-notification-two-tone', <NotificationTwoTone />],
    ['antd-tool-two-tone', <ToolTwoTone />],
    ['antd-down', <DownOutlined />],
    ['antd-up', <UpOutlined />],
    ['antd-left', <LeftOutlined />],
    ['antd-right', <RightOutlined />],
    ['antd-caret-up', <CaretUpOutlined />],
    ['antd-caret-down', <CaretDownOutlined />],
    ['antd-caret-left', <CaretLeftOutlined />],
    ['antd-caret-right', <CaretRightOutlined />],
    ['antd-up-circle', <UpCircleOutlined />],
    ['antd-down-circle', <DownCircleOutlined />],
    ['antd-left-circle', <LeftCircleOutlined />],
    ['antd-right-circle', <RightCircleOutlined />],
    ['antd-enter', <EnterOutlined />],
    ['antd-retweet', <RetweetOutlined />],
    ['antd-warning', <WarningOutlined />],
    ['antd-form', <FormOutlined />],
    ['antd-copy', <CopyOutlined />],
    ['antd-scissor', <ScissorOutlined />],
    ['antd-snippets', <SnippetsOutlined />],
    ['antd-diff', <DiffOutlined />],
    ['antd-ordered-list', <OrderedListOutlined />],
    ['antd-unordered-list', <UnorderedListOutlined />],
    ['antd-sliders', <SlidersOutlined />],
    ['antd-audit', <AuditOutlined />],
    ['antd-border', <BorderOutlined />],
    ['antd-contacts', <ContactsOutlined />],
    ['antd-container', <ContainerOutlined />],
    ['antd-delivered-procedure', <DeliveredProcedureOutlined />],
    ['antd-pause', <PauseOutlined />],
    ['antd-step-backward', <StepBackwardOutlined />],
    ['antd-step-forward', <StepForwardOutlined />],
    ['antd-fast-forward', <FastForwardOutlined />],
    ['antd-fast-backward', <FastBackwardOutlined />],
    ['md-star-half', <MdStarHalf />],
    ['md-star-border', <MdStarBorder />],
    ['md-star', <MdStar />],
    ['md-people', <MdPeople />],
    ['md-plus-one', <MdPlusOne />],
    ['md-notifications', <MdNotifications />],
    ['md-pin-drop', <MdPinDrop />],
    ['md-layers-clear', <MdLayersClear />],
    ['md-layers', <MdLayers />],
    ['md-edit-location', <MdEditLocation />],
    ['md-tune', <MdTune />],
    ['md-transform', <MdTransform />],
    ['md-timer-off', <MdTimerOff />],
    ['md-timer', <MdTimer />],
    ['md-file-upload', <MdFileUpload />],
    ['md-file-download', <MdFileDownload />],
    ['md-create-new-folder', <MdCreateNewFolder />],
    ['md-cloud-upload', <MdCloudUpload />],
    ['md-cloud-queue', <MdCloudQueue />],
    ['md-cloud-download', <MdCloudDownload />],
    ['md-cloud-done', <MdCloudDone />],
    ['md-insert-chart', <MdInsertChart />],
    ['md-functions', <MdFunctions />],
    ['md-format-quote', <MdFormatQuote />],
    ['md-attach-file', <MdAttachFile />],
    ['md-storage', <MdStorage />],
    ['md-save', <MdSave />],
    ['md-remove-circle-outline', <MdRemoveCircleOutline />],
    ['md-remove-circle', <MdRemoveCircle />],
    ['md-remove', <MdRemove />],
    ['md-low-priority', <MdLowPriority />],
    ['md-link', <MdLink />],
    ['md-gesture', <MdGesture />],
    ['md-forward', <MdForward />],
    ['md-flag', <MdFlag />],
    ['md-drafts', <MdDrafts />],
    ['md-create', <MdCreate />],
    ['md-content-paste', <MdContentPaste />],
    ['md-content-cut', <MdContentCut />],
    ['md-content-copy', <MdContentCopy />],
    ['md-clear', <MdClear />],
    ['md-block', <MdBlock />],
    ['md-backspace', <MdBackspace />],
    ['md-add-box', <MdAddBox />],
    ['md-add', <MdAdd />],
    ['md-add-circle-outline', <MdAddCircleOutline />],
    ['md-add-circle', <MdAddCircle />],
    ['md-location-on', <MdLocationOn />],
    ['md-mail-outline', <MdMailOutline />],
    ['md-email', <MdEmail />],
    ['md-not-interested', <MdNotInterested />],
    ['md-library-books', <MdLibraryBooks />],
    ['md-library-add', <MdLibraryAdd />],
    ['md-equalizer', <MdEqualizer />],
    ['md-add-alert', <MdAddAlert />],
    ['md-visibility-off', <MdVisibilityOff />],
    ['md-visibility', <MdVisibility />],
    ['md-verified-user', <MdVerifiedUser />],
    ['md-update', <MdUpdate />],
    ['md-trending-up', <MdTrendingUp />],
    ['md-trending-flat', <MdTrendingFlat />],
    ['md-trending-down', <MdTrendingDown />],
    ['md-translate', <MdTranslate />],
    ['md-toc', <MdToc />],
    ['md-timeline', <MdTimeline />],
    ['md-thumb-up', <MdThumbUp />],
    ['md-thumb-down', <MdThumbDown />],
    ['md-swap-vert', <MdSwapVert />],
    ['md-swap-horiz', <MdSwapHoriz />],
    ['md-supervisor-account', <MdSupervisorAccount />],
    ['md-subject', <MdSubject />],
    ['md-settings', <MdSettings />],
    ['md-search', <MdSearch />],
    ['md-schedule', <MdSchedule />],
    ['md-restore', <MdRestore />],
    ['md-query-builder', <MdQueryBuilder />],
    ['md-power-settings-new', <MdPowerSettingsNew />],
    ['md-opacity', <MdOpacity />],
    ['md-note-add', <MdNoteAdd />],
    ['md-lock-outline', <MdLockOutline />],
    ['md-lock-open', <MdLockOpen />],
    ['md-list', <MdList />],
    ['md-lightbulb-outline', <MdLightbulbOutline />],
    ['md-launch', <MdLaunch />],
    ['md-label-outline', <MdLabelOutline />],
    ['md-label', <MdLabel />],
    ['md-input', <MdInput />],
    ['md-info-outline', <MdInfoOutline />],
    ['md-info', <MdInfo />],
    ['md-hourglass', <MdHourglassEmpty />],
    ['md-home', <MdHome />],
    ['md-history', <MdHistory />],
    ['md-highlight-off', <MdHighlightOff />],
    ['md-help-outline', <MdHelpOutline />],
    ['md-help', <MdHelp />],
    ['md-get-app', <MdGetApp />],
    ['md-translate', <MdGTranslate />],
    ['md-fingerprint', <MdFingerprint />],
    ['md-findIn-page', <MdFindInPage />],
    ['md-favorite-border', <MdFavoriteBorder />],
    ['md-favorite', <MdFavorite />],
    ['md-extension', <MdExtension />],
    ['md-explore', <MdExplore />],
    ['md-exit-to-app', <MdExitToApp />],
    ['md-event', <MdEvent />],
    ['md-description', <MdDescription />],
    ['md-delete-forever', <MdDeleteForever />],
    ['md-delete', <MdDelete />],
    ['md-dashboard', <MdDashboard />],
    ['md-code', <MdCode />],
    ['md-build', <MdBuild />],
    ['md-bug-report', <MdBugReport />],
    ['md-assignment', <MdAssignment />],
    ['md-assessment', <MdAssessment />],
    ['md-alarm-on', <MdAlarmOn />],
    ['md-alarm-off', <MdAlarmOff />],
    ['md-alarm-add', <MdAlarmAdd />],
    ['md-alarm', <MdAlarm />],
    ['md-account-circle', <MdAccountCircle />],
    ['fc-vlc', <FcVlc />],
    ['fc-view-details', <FcViewDetails />],
    ['fc-upload', <FcUpload />],
    ['fc-tree-structure', <FcTreeStructure />],
    ['fc-timeline', <FcTimeline />],
    ['fc-template', <FcTemplate />],
    ['fc-survey', <FcSurvey />],
    ['fc-signature', <FcSignature />],
    ['fc-share', <FcShare />],
    ['fc-services', <FcServices />],
    ['fc-rules', <FcRules />],
    ['fc-questions', <FcQuestions />],
    ['fc-process', <FcProcess />],
    ['fc-plus', <FcPlus />],
    ['fc-overtime', <FcOvertime />],
    ['fc-organization', <FcOrganization />],
    ['fc-numerical-sorting21', <FcNumericalSorting21 />],
    ['fc-numerical-sorting12', <FcNumericalSorting12 />],
    ['fc-multiple-inputs', <FcMultipleInputs />],
    ['fc-mind-map', <FcMindMap />],
    ['fc-menu', <FcMenu />],
    ['fc-list', <FcList />],
    ['fc-like', <FcLike />],
    ['fc-like-placeholder', <FcLikePlaceholder />],
    ['fc-info', <FcInfo />],
    ['fc-import', <FcImport />],
    ['fc-image-file', <FcImageFile />],
    ['fc-idea', <FcIdea />],
    ['fc-home', <FcHome />],
    ['fc-high-priority', <FcHighPriority />],
    ['fc-low-priority', <FcLowPriority />],
    ['fc-genealogy', <FcGenealogy />],
    ['fc-full-trash', <FcFullTrash />],
    ['fc-document-search', <FcFinePrint />],
    ['fc-file', <FcFile />],
    ['fc-faq', <FcFaq />],
    ['fc-export', <FcExport />],
    ['fc-empty-trash', <FcEmptyTrash />],
    ['fc-download', <FcDownload />],
    ['fc-document', <FcDocument />],
    ['fc-deployment', <FcDeployment />],
    ['fc-delete-database', <FcDeleteDatabase />],
    ['fc-conference-call', <FcConferenceCall />],
    ['fc-database', <FcDatabase />],
    ['fc-data-protection', <FcDataProtection />],
    ['fc-data-encryption', <FcDataEncryption />],
    ['fc-data-configuration', <FcDataConfiguration />],
    ['fc-data-backup', <FcDataBackup />],
    ['fc-checkmark', <FcCheckmark />],
    ['fc-cancel', <FcCancel />],
    ['fc-briefcase', <FcBriefcase />],
    ['fc-binoculars', <FcBinoculars />],
    ['fc-automatic', <FcAutomatic />],
    ['fc-alphabetical-sorting-za', <FcAlphabeticalSortingZa />],
    ['fc-alphabetical-sorting-az', <FcAlphabeticalSortingAz />],
    ['fc-add-database', <FcAddDatabase />],
    ['fc-accept-database', <FcAcceptDatabase />],
    ['fc-about', <FcAbout />],
    ['fc-radar-chart', <FcRadarPlot />],
    ['fc-scatter-chart', <FcScatterPlot />],
    ['fc-pie-chart', <FcPieChart />],
    ['fc-line-chart', <FcLineChart />],
    ['fc-flow-chart', <FcFlowChart />],
    ['fc-doughnut-chart', <FcDoughnutChart />],
    ['fc-bar-chart', <FcBarChart />],
    ['fc-area-chart', <FcAreaChart />],
    ['fc-line-bar-chart', <FcComboChart />],
    ['fc-workflow', <FcWorkflow />],
    ['fc-todo-list', <FcTodoList />],
    ['fc-synchronize', <FcSynchronize />],
    ['fc-repair', <FcSupport />],
    ['fc-statistics', <FcStatistics />],
    ['fc-settings', <FcSettings />],
    ['fc-search', <FcSearch />],
    ['fc-serial-tasks', <FcSerialTasks />],
    ['fc-safe', <FcSafe />],
    ['fc-negative-dynamic', <FcNegativeDynamic />],
    ['fc-positive-dynamic', <FcPositiveDynamic />],
    ['fc-planner', <FcPlanner />],
    ['fc-parallel-tasks', <FcParallelTasks />],
    ['fc-org-unit', <FcOrgUnit />],
    ['fc-opened-folder', <FcOpenedFolder />],
    ['fc-ok', <FcOk />],
    ['fc-inspection', <FcInspection />],
    ['fc-globe', <FcGlobe />],
    ['fc-folder', <FcFolder />],
    ['fc-electronics', <FcElectronics />],
    ['fc-data-sheet', <FcDataSheet />],
    ['fc-command-line', <FcCommandLine />],
    ['fc-calendar', <FcCalendar />],
    ['fc-calculator', <FcCalculator />],
    ['fc-bullish', <FcBullish />],
    ['fc-bearish', <FcBearish />],
    ['fc-bookmark', <FcBookmark />],
    ['fc-approval', <FcApproval />],
    ['fc-advertising', <FcAdvertising />],
    ['di-linux', <DiLinux />],
    ['di-python', <DiPython />],
    ['di-chrome', <DiChrome />],
    ['di-database', <DiDatabase />],
    ['di-firefox', <DiFirefox />],
    ['di-markdown', <DiMarkdown />],
    ['di-postgresql', <DiPostgresql />],
    ['di-terminal', <DiTerminal />],
    ['di-windows', <DiWindows />],
    ['bi-table', <BiTable />],
    ['bi-analyse', <BiAnalyse />],
    ['bi-layer', <BiLayer />],
    ['bi-layer-minus', <BiLayerMinus />],
    ['bi-layer-plus', <BiLayerPlus />],
    ['bs-list-task', <BsListTask />],
    ['bs-list-check', <BsListCheck />],
    ['bs-link', <BsLink />],
    ['bs-link-45-deg', <BsLink45Deg />],
    ['bs-envelope-open', <BsEnvelopeOpen />],
    ['bs-envelope', <BsEnvelope />],
    ['bs-alarm', <BsAlarm />],
    ['im-earth', <ImEarth />],
    ['im-sphere', <ImSphere />],
    ['gi-mesh-network', <GiMeshNetwork style={{ transform: 'scale(1.2)' }} />],
    ['pi-circle', <PiCircle />],
    ['pi-polygon', <PiPolygon />],
    ['pi-map-pin', <PiMapPin />],
    ['pi-line-segment', <PiLineSegment />],
    ['pi-line-segments', <PiLineSegments />],
    ['pi-trash-simple', <PiTrashSimple />],
    ['pi-trash', <PiTrash />],
    ['pi-ruler', <PiRuler />],
    ['pi-selection', <PiSelection />],
    ['pi-selection-slash', <PiSelectionSlash />],
    ['pi-square-split-horizontal', <PiSquareSplitHorizontal />],
    ['pi-square-split-vertical', <PiSquareSplitVertical />],
    ['pi-stack-simple', <PiStackSimple />],
    ['pi-stack', <PiStack />],
    ['pi-navigation-arrow', <PiNavigationArrow />],
    ['pi-map-trifold', <PiMapTrifold />],
    ['pi-info', <PiInfo />],
    ['pi-lock-key-open', <PiLockKeyOpen />],
    ['pi-lock-key', <PiLockKey />],
    ['pi-gear', <PiGear />],
    ['pi-airplane', <PiAirplane />],
    ['pi-anchor-simple', <PiAnchorSimple />],
    ['pi-arrow-arc-left', <PiArrowArcLeft />],
    ['pi-arrow-arc-right', <PiArrowArcRight />],
    ['pi-arrow-clockwise', <PiArrowClockwise />],
    ['pi-arrow-counter-clockwise', <PiArrowCounterClockwise />],
    ['pi-barricade', <PiBarricade />],
    ['pi-binoculars', <PiBinoculars />],
    ['pi-bounding-box', <PiBoundingBox />],
    ['pi-broom', <PiBroom />],
    ['pi-buildings', <PiBuildings />],
    ['pi-calculator', <PiCalculator />],
    ['pi-camera', <PiCamera />],
    ['pi-circuitry', <PiCircuitry />],
    ['pi-clipboard', <PiClipboard />],
    ['pi-compass', <PiCompass />],
    ['pi-copy', <PiCopy />],
    ['pi-cpu', <PiCpu />],
    ['pi-crosshair', <PiCrosshair />],
    ['pi-cube-focus', <PiCubeFocus />],
    ['pi-cube', <PiCube />],
    ['pi-cursor', <PiCursor />],
    ['pi-database', <PiDatabase />],
    ['pi-eye-slash', <PiEyeSlash />],
    ['pi-eye', <PiEye />],
    ['pi-faders', <PiFaders />],
    ['pi-floppy-disk', <PiFloppyDisk />],
    ['pi-dots-three-vertical', <PiDotsThreeVertical />],
    ['pi-dots-three', <PiDotsThree />],
    ['pi-math-operations', <PiMathOperations />],
    ['pi-plus', <PiPlus />],
    ['pi-minus', <PiMinus />],
    ['pi-path', <PiPath />],
    ['si-gitee', <SiGitee />]
])


export { str2Icon }