import {
    HomeOutlined,
    BarChartOutlined,
    PieChartOutlined,
    DotChartOutlined,
    LineChartOutlined,
    ApartmentOutlined,
    AppstoreOutlined,
    AppstoreAddOutlined,
    BellOutlined,
    CalculatorOutlined,
    DatabaseOutlined,
    CalendarOutlined,
    HistoryOutlined,
    SearchOutlined,
    FileSearchOutlined,
    CloudDownloadOutlined,
    CloudServerOutlined,
    CloudUploadOutlined,
    SwapOutlined,
    RollbackOutlined,
    LoginOutlined,
    LogoutOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    FullscreenOutlined,
    FullscreenExitOutlined,
    QuestionCircleOutlined,
    PlusCircleOutlined,
    MinusCircleOutlined,
    InfoCircleOutlined,
    ExclamationCircleOutlined,
    CloseCircleOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    StopOutlined,
    EditOutlined,
    DeleteOutlined,
    HighlightOutlined,
    RedoOutlined,
    UndoOutlined,
    ZoomInOutlined,
    ZoomOutOutlined,
    SortAscendingOutlined,
    SortDescendingOutlined,
    AreaChartOutlined,
    BoxPlotOutlined,
    FallOutlined,
    RiseOutlined,
    StockOutlined,
    GithubOutlined,
    WeiboCircleOutlined,
    AlipayOutlined,
    AlipayCircleOutlined,
    AccountBookOutlined,
    AlertOutlined,
    ApiOutlined,
    BarsOutlined,
    BookOutlined,
    CameraOutlined,
    ClearOutlined,
    CloudOutlined,
    ClusterOutlined,
    CodeOutlined,
    CommentOutlined,
    CompassOutlined,
    ConsoleSqlOutlined,
    ControlOutlined,
    DashboardOutlined,
    ExportOutlined,
    ImportOutlined,
    FunctionOutlined,
    GlobalOutlined,
    HourglassOutlined,
    KeyOutlined,
    LoadingOutlined,
    LockOutlined,
    MailOutlined,
    MenuOutlined,
    NotificationOutlined,
    NumberOutlined,
    PoweroffOutlined,
    QrcodeOutlined,
    ReadOutlined,
    ReloadOutlined,
    SaveOutlined,
    RocketOutlined,
    ScheduleOutlined,
    SendOutlined,
    SettingOutlined,
    SyncOutlined,
    TeamOutlined,
    ToolOutlined,
    UnlockOutlined,
    UserOutlined
} from '@ant-design/icons';

import {
    BsAlarm,
    BsEnvelope,
    BsEnvelopeOpen,
    BsLink,
    BsLink45Deg,
    BsListCheck,
    BsListTask
} from "react-icons/bs";
import {
    BiAnalyse,
    BiTable
} from "react-icons/bi";
import { DiPython, DiLinux } from "react-icons/di";
import {
    FcAdvertising,
    FcApproval,
    FcBookmark,
    FcBearish,
    FcBullish,
    FcCalculator,
    FcCalendar,
    FcCommandLine,
    FcDataSheet,
    FcElectronics,
    FcFolder,
    FcGlobe,
    FcInfo,
    FcInspection,
    FcOk,
    FcOpenedFolder,
    FcOrgUnit,
    FcParallelTasks,
    FcPlanner,
    FcNegativeDynamic,
    FcPositiveDynamic,
    FcSafe,
    FcSerialTasks,
    FcSearch,
    FcSettings,
    FcStatistics,
    FcSupport,
    FcSynchronize,
    FcTodoList,
    FcWorkflow,
    FcComboChart,
    FcAreaChart,
    FcBarChart,
    FcDoughnutChart,
    FcFlowChart,
    FcLineChart,
    FcPieChart,
    FcScatterPlot,
    FcRadarPlot,
    FcAbout,
    FcAcceptDatabase,
    FcAddDatabase,
    FcAlphabeticalSortingAz,
    FcAlphabeticalSortingZa,
    FcAutomatic,
    FcBinoculars,
    FcBriefcase,
    FcCancel,
    FcCheckmark,
    FcDataBackup,
    FcDataConfiguration,
    FcDataEncryption,
    FcConferenceCall,
    FcDataProtection,
    FcDatabase,
    FcDeleteDatabase,
    FcDeployment,
    FcDocument,
    FcDownload,
    FcEmptyTrash,
    FcExport,
    FcFaq,
    FcFile,
    FcFinePrint,
    FcFullTrash,
    FcGenealogy,
    FcHighPriority,
    FcHome,
    FcIdea,
    FcImageFile,
    FcImport,
    FcInfo,
    FcLikePlaceholder,
    FcLike,
    FcList,
    FcLowPriority,
    FcMenu,
    FcMindMap,
    FcMultipleInputs,
    FcNumericalSorting12,
    FcNumericalSorting21,
    FcOrganization
} from "react-icons/fc";
import { ImEarth } from "react-icons/im";
import { GiMeshNetwork } from "react-icons/gi";


const str2Icon = new Map([
    ['fc-organization', <FcOrganization />],
    ['fc-numerical-sorting21', <FcNumericalSorting21 />],
    ['fc-numerical-sorting12', <FcNumericalSorting12 />],
    ['fc-multiple-inputs', <FcMultipleInputs />],
    ['fc-mind-map', <FcMindMap />],
    ['fc-menu', <FcMenu />],
    ['fc-list', <FcList />],
    ['fc-like', <FcLike />],
    ['fc-like-placeholder', <FcLikePlaceholder />],
    ['fc-info', <FcInfo />],
    ['fc-import', <FcImport />],
    ['fc-image-file', <FcImageFile />],
    ['fc-idea', <FcIdea />],
    ['fc-home', <FcHome />],
    ['fc-high-priority', <FcHighPriority />],
    ['fc-low-priority', <FcLowPriority />],
    ['fc-genealogy', <FcGenealogy />],
    ['fc-full-trash', <FcFullTrash />],
    ['fc-document-search', <FcFinePrint />],
    ['fc-file', <FcFile />],
    ['fc-faq', <FcFaq />],
    ['fc-export', <FcExport />],
    ['fc-empty-trash', <FcEmptyTrash />],
    ['fc-download', <FcDownload />],
    ['fc-document', <FcDocument />],
    ['fc-deployment', <FcDeployment />],
    ['fc-delete-database', <FcDeleteDatabase />],
    ['fc-conference-call', <FcConferenceCall />],
    ['fc-database', <FcDatabase />],
    ['fc-data-protection', <FcDataProtection />],
    ['fc-data-encryption', <FcDataEncryption />],
    ['fc-data-configuration', <FcDataConfiguration />],
    ['fc-data-backup', <FcDataBackup />],
    ['fc-checkmark', <FcCheckmark />],
    ['fc-cancel', <FcCancel />],
    ['fc-briefcase', <FcBriefcase />],
    ['fc-binoculars', <FcBinoculars />],
    ['fc-automatic', <FcAutomatic />],
    ['fc-alphabetical-sorting-za', <FcAlphabeticalSortingZa />],
    ['fc-alphabetical-sorting-az', <FcAlphabeticalSortingAz />],
    ['fc-add-database', <FcAddDatabase />],
    ['fc-accept-database', <FcAcceptDatabase />],
    ['fc-about', <FcAbout />],
    ['fc-radar-chart', <FcRadarPlot />],
    ['fc-scatter-chart', <FcScatterPlot />],
    ['fc-pie-chart', <FcPieChart />],
    ['fc-line-chart', <FcLineChart />],
    ['fc-flow-chart', <FcFlowChart />],
    ['fc-doughnut-chart', <FcDoughnutChart />],
    ['fc-bar-chart', <FcBarChart />],
    ['fc-area-chart', <FcAreaChart />],
    ['fc-line-bar-chart', <FcComboChart />],
    ['fc-workflow', <FcWorkflow />],
    ['fc-todo-list', <FcTodoList />],
    ['fc-synchronize', <FcSynchronize />],
    ['fc-repair', <FcSupport />],
    ['fc-statistics', <FcStatistics />],
    ['fc-settings', <FcSettings />],
    ['fc-search', <FcSearch />],
    ['fc-serial-tasks', <FcSerialTasks />],
    ['fc-safe', <FcSafe />],
    ['fc-negative-dynamic', <FcNegativeDynamic />],
    ['fc-positive-dynamic', <FcPositiveDynamic />],
    ['fc-planner', <FcPlanner />],
    ['fc-parallel-tasks', <FcParallelTasks />],
    ['fc-org-unit', <FcOrgUnit />],
    ['fc-opened-folder', <FcOpenedFolder />],
    ['fc-ok', <FcOk />],
    ['fc-inspection', <FcInspection />],
    ['fc-info', <FcInfo />],
    ['fc-globe', <FcGlobe />],
    ['fc-folder', <FcFolder />],
    ['fc-electronics', <FcElectronics />],
    ['fc-data-sheet', <FcDataSheet />],
    ['fc-command-line', <FcCommandLine />],
    ['fc-calendar', <FcCalendar />],
    ['fc-calculator', <FcCalculator />],
    ['fc-bullish', <FcBullish />],
    ['fc-bearish', <FcBearish />],
    ['fc-bookmark', <FcBookmark />],
    ['fc-approval', <FcApproval />],
    ['fc-advertising', <FcAdvertising />],
    ['di-linux', <DiLinux />],
    ['di-python', <DiPython />],
    ['bi-table', <BiTable />],
    ['bi-analyse', <BiAnalyse />],
    ['bs-list-task', <BsListTask />],
    ['bs-list-check', <BsListCheck />],
    ['bs-link', <BsLink />],
    ['bs-link-45-deg', <BsLink45Deg />],
    ['bs-envelope-open', <BsEnvelopeOpen />],
    ['bs-envelope', <BsEnvelope />],
    ['bs-alarm', <BsAlarm />],
    ['user', <UserOutlined />],
    ['unlock', <UnlockOutlined />],
    ['repair', <ToolOutlined />],
    ['team', <TeamOutlined />],
    ['sync', <SyncOutlined />],
    ['setting', <SettingOutlined />],
    ['send', <SendOutlined />],
    ['schedule', <ScheduleOutlined />],
    ['save', <SaveOutlined />],
    ['rocket', <RocketOutlined />],
    ['reload', <ReloadOutlined />],
    ['read', <ReadOutlined />],
    ['qrcode', <QrcodeOutlined />],
    ['power-off', <PoweroffOutlined />],
    ['number', <NumberOutlined />],
    ['notification', <NotificationOutlined />],
    ['menu', <MenuOutlined />],
    ['mail', <MailOutlined />],
    ['lock', <LockOutlined />],
    ['loading', <LoadingOutlined />],
    ['key', <KeyOutlined />],
    ['hourglass', <HourglassOutlined />],
    ['global', <GlobalOutlined />],
    ['function', <FunctionOutlined />],
    ['import', <ImportOutlined />],
    ['export', <ExportOutlined />],
    ['dashboard', <DashboardOutlined />],
    ['control', <ControlOutlined />],
    ['console-sql', <ConsoleSqlOutlined />],
    ['compass', <CompassOutlined />],
    ['comment', <CommentOutlined />],
    ['code', <CodeOutlined />],
    ['cluster', <ClusterOutlined />],
    ['clear', <ClearOutlined />],
    ['camera', <CameraOutlined />],
    ['book', <BookOutlined />],
    ['catalog', <BarsOutlined />],
    ['api', <ApiOutlined />],
    ['alert', <AlertOutlined />],
    ['account-book', <AccountBookOutlined />],
    ['alipay', <AlipayOutlined />],
    ['alipay-circle', <AlipayCircleOutlined />],
    ['weibo', <WeiboCircleOutlined />],
    ['github', <GithubOutlined />],
    ['fall', <FallOutlined />],
    ['rise', <RiseOutlined />],
    ['stock', <StockOutlined />],
    ['home', <HomeOutlined />],
    ['area-chart', <AreaChartOutlined />],
    ['bar-chart', <BarChartOutlined />],
    ['pie-chart', <PieChartOutlined />],
    ['box-plot', <BoxPlotOutlined />],
    ['dot-chart', <DotChartOutlined />],
    ['line-chart', <LineChartOutlined />],
    ['apartment', <ApartmentOutlined />],
    ['app-store', <AppstoreOutlined />],
    ['app-store-add', <AppstoreAddOutlined />],
    ['bell', <BellOutlined />],
    ['calculator', <CalculatorOutlined />],
    ['calendar', <CalendarOutlined />],
    ['database', <DatabaseOutlined />],
    ['history', <HistoryOutlined />],
    ['search', <SearchOutlined />],
    ['file-search', <FileSearchOutlined />],
    ['cloud', <CloudOutlined />],
    ['cloud-upload', <CloudUploadOutlined />],
    ['cloud-download', <CloudDownloadOutlined />],
    ['cloud-server', <CloudServerOutlined />],
    ['swap', <SwapOutlined />],
    ['im-earth', <ImEarth />],
    ['gi-mesh-network', <GiMeshNetwork style={{ zoom: 1.2 }} />],
    ['rollback', <RollbackOutlined />],
    ['login', <LoginOutlined />],
    ['logout', <LogoutOutlined />],
    ['menu-fold', <MenuFoldOutlined />],
    ['menu-unfold', <MenuUnfoldOutlined />],
    ['full-screen', <FullscreenOutlined />],
    ['full-screen-exit', <FullscreenExitOutlined />],
    ['question-circle', <QuestionCircleOutlined />],
    ['plus-circle', <PlusCircleOutlined />],
    ['minus-circle', <MinusCircleOutlined />],
    ['info-circle', <InfoCircleOutlined />],
    ['exclamation-circle', <ExclamationCircleOutlined />],
    ['close-circle', <CloseCircleOutlined />],
    ['check-circle', <CheckCircleOutlined />],
    ['clock-circle', <ClockCircleOutlined />],
    ['stop', <StopOutlined />],
    ['edit', <EditOutlined />],
    ['delete', <DeleteOutlined />],
    ['highlight', <HighlightOutlined />],
    ['redo', <RedoOutlined />],
    ['undo', <UndoOutlined />],
    ['zoom-in', <ZoomInOutlined />],
    ['zoom-out', <ZoomOutOutlined />],
    ['sort-ascending', <SortAscendingOutlined />],
    ['sort-descending', <SortDescendingOutlined />]
])

export { str2Icon }