import {
    HomeOutlined,
    BarChartOutlined,
    PieChartOutlined,
    DotChartOutlined,
    LineChartOutlined,
    ApartmentOutlined,
    AppstoreOutlined,
    AppstoreAddOutlined,
    BellOutlined,
    CalculatorOutlined,
    DatabaseOutlined,
    CalendarOutlined,
    HistoryOutlined,
    SearchOutlined,
    FileSearchOutlined,
    CloudDownloadOutlined,
    CloudServerOutlined,
    CloudUploadOutlined,
    SwapOutlined,
    RollbackOutlined,
    LoginOutlined,
    TableOutlined,
    LogoutOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    FullscreenOutlined,
    FullscreenExitOutlined,
    QuestionCircleOutlined,
    PlusCircleOutlined,
    MinusCircleOutlined,
    InfoCircleOutlined,
    ExclamationCircleOutlined,
    CloseCircleOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    StopOutlined,
    EditOutlined,
    DeleteOutlined,
    HighlightOutlined,
    RedoOutlined,
    UndoOutlined,
    ZoomInOutlined,
    ZoomOutOutlined,
    SortAscendingOutlined,
    SortDescendingOutlined,
    AreaChartOutlined,
    BoxPlotOutlined,
    FallOutlined,
    RiseOutlined,
    StockOutlined,
    GithubOutlined,
    WeiboCircleOutlined,
    AlipayOutlined,
    AlipayCircleOutlined,
    AccountBookOutlined,
    AlertOutlined,
    ApiOutlined,
    BarsOutlined,
    BookOutlined,
    CameraOutlined,
    ClearOutlined,
    CloudOutlined,
    ClusterOutlined,
    CodeOutlined,
    CommentOutlined,
    CompassOutlined,
    ConsoleSqlOutlined,
    ControlOutlined,
    DashboardOutlined,
    ExportOutlined,
    ImportOutlined,
    FunctionOutlined,
    GlobalOutlined,
    HourglassOutlined,
    KeyOutlined,
    LoadingOutlined,
    LockOutlined,
    MailOutlined,
    MenuOutlined,
    NotificationOutlined,
    NumberOutlined,
    PoweroffOutlined,
    QrcodeOutlined,
    ReadOutlined,
    ReloadOutlined,
    SaveOutlined,
    RocketOutlined,
    ScheduleOutlined,
    SendOutlined,
    SettingOutlined,
    SyncOutlined,
    TeamOutlined,
    ToolOutlined,
    UnlockOutlined,
    UserOutlined
} from '@ant-design/icons';

import {
    BsAlarm,
    BsEnvelope,
    BsEnvelopeOpen,
    BsLink,
    BsLink45Deg,
    BsListCheck,
    BsListTask
} from "react-icons/bs";
import {
    BiAnalyse,
    BiTable
} from "react-icons/bi";
import { DiPython, DiLinux } from "react-icons/di";
import {
    FcAdvertising,
    FcApproval,
    FcBookmark,
    FcBearish,
    FcBullish,
    FcCalculator,
    FcCalendar,
    FcCommandLine,
    FcDataSheet,
    FcElectronics,
    FcFolder,
    FcGlobe,
    FcInspection,
    FcOk,
    FcOpenedFolder,
    FcOrgUnit,
    FcParallelTasks,
    FcPlanner,
    FcNegativeDynamic,
    FcPositiveDynamic,
    FcSafe,
    FcSerialTasks,
    FcSearch,
    FcStatistics,
    FcSupport,
    FcSynchronize,
    FcTodoList,
    FcWorkflow,
    FcComboChart,
    FcAreaChart,
    FcBarChart,
    FcDoughnutChart,
    FcFlowChart,
    FcLineChart,
    FcPieChart,
    FcScatterPlot,
    FcRadarPlot,
    FcAbout,
    FcAcceptDatabase,
    FcAddDatabase,
    FcAlphabeticalSortingAz,
    FcAlphabeticalSortingZa,
    FcAutomatic,
    FcBinoculars,
    FcBriefcase,
    FcCancel,
    FcCheckmark,
    FcDataBackup,
    FcDataConfiguration,
    FcDataEncryption,
    FcConferenceCall,
    FcDataProtection,
    FcDatabase,
    FcDeleteDatabase,
    FcDeployment,
    FcDocument,
    FcDownload,
    FcEmptyTrash,
    FcExport,
    FcFaq,
    FcFile,
    FcFinePrint,
    FcFullTrash,
    FcGenealogy,
    FcHighPriority,
    FcHome,
    FcIdea,
    FcImageFile,
    FcImport,
    FcInfo,
    FcLikePlaceholder,
    FcLike,
    FcList,
    FcLowPriority,
    FcMenu,
    FcMindMap,
    FcMultipleInputs,
    FcNumericalSorting12,
    FcNumericalSorting21,
    FcOrganization,
    FcOvertime,
    FcPlus,
    FcProcess,
    FcQuestions,
    FcRules,
    FcServices,
    FcSettings,
    FcShare,
    FcSignature,
    FcSurvey,
    FcTemplate,
    FcTimeline,
    FcTreeStructure,
    FcUpload,
    FcViewDetails,
    FcVlc
} from "react-icons/fc";
import {
    MdAccountCircle,
    MdAlarm,
    MdAlarmAdd,
    MdAlarmOff,
    MdAlarmOn,
    MdAssessment,
    MdAssignment,
    MdBugReport,
    MdBuild,
    MdCode,
    MdDashboard,
    MdDelete,
    MdDeleteForever,
    MdDescription,
    MdEvent,
    MdExitToApp,
    MdExplore,
    MdExtension,
    MdFavorite,
    MdFavoriteBorder,
    MdFindInPage,
    MdFingerprint,
    MdGTranslate,
    MdGetApp,
    MdHelp,
    MdHelpOutline,
    MdHighlightOff,
    MdHistory,
    MdHome,
    MdHourglassEmpty,
    MdInfo,
    MdInfoOutline,
    MdInput,
    MdLabel,
    MdLabelOutline,
    MdLaunch,
    MdLightbulbOutline,
    MdList,
    MdLockOpen,
    MdLockOutline,
    MdNoteAdd,
    MdOpacity,
    MdPowerSettingsNew,
    MdQueryBuilder,
    MdRestore,
    MdSchedule,
    MdSearch,
    MdSettings,
    MdSubject,
    MdSupervisorAccount,
    MdSwapHoriz,
    MdSwapVert,
    MdThumbDown,
    MdThumbUp,
    MdTimeline,
    MdToc,
    MdTranslate,
    MdTrendingDown,
    MdTrendingFlat,
    MdTrendingUp,
    MdUpdate,
    MdVerifiedUser,
    MdVisibility,
    MdVisibilityOff,
    MdAddAlert,
    MdEqualizer,
    MdLibraryAdd,
    MdLibraryBooks,
    MdNotInterested,
    MdEmail,
    MdMailOutline,
    MdLocationOn,
    MdAddCircle,
    MdAddCircleOutline,
    MdAdd,
    MdAddBox,
    MdBackspace,
    MdBlock,
    MdClear,
    MdContentCopy,
    MdContentCut,
    MdContentPaste,
    MdCreate,
    MdDrafts,
    MdFlag,
    MdForward,
    MdGesture,
    MdLink,
    MdLowPriority,
    MdRemove,
    MdRemoveCircle,
    MdRemoveCircleOutline,
    MdSave,
    MdStorage,
    MdAttachFile,
    MdFormatQuote,
    MdFunctions,
    MdInsertChart,
    MdCloudDone,
    MdCloudDownload,
    MdCloudQueue,
    MdCloudUpload,
    MdCreateNewFolder,
    MdFileDownload,
    MdFileUpload,
    MdTimer,
    MdTimerOff,
    MdTransform,
    MdTune,
    MdEditLocation,
    MdLayers,
    MdLayersClear,
    MdPinDrop,
    MdNotifications,
    MdPlusOne,
    MdPeople,
    MdStar,
    MdStarBorder,
    MdStarHalf
} from "react-icons/md";
import { ImEarth } from "react-icons/im";
import { GiMeshNetwork } from "react-icons/gi";

const str2Icon = new Map([
    ['md-star-half', <MdStarHalf />],
    ['md-star-border', <MdStarBorder />],
    ['md-star', <MdStar />],
    ['md-people', <MdPeople />],
    ['md-plus-one', <MdPlusOne />],
    ['md-notifications', <MdNotifications />],
    ['md-pin-drop', <MdPinDrop />],
    ['md-layers-clear', <MdLayersClear />],
    ['md-layers', <MdLayers />],
    ['md-edit-location', <MdEditLocation />],
    ['md-tune', <MdTune />],
    ['md-transform', <MdTransform />],
    ['md-timer-off', <MdTimerOff />],
    ['md-timer', <MdTimer />],
    ['md-file-upload', <MdFileUpload />],
    ['md-file-download', <MdFileDownload />],
    ['md-create-new-folder', <MdCreateNewFolder />],
    ['md-cloud-upload', <MdCloudUpload />],
    ['md-cloud-queue', <MdCloudQueue />],
    ['md-cloud-download', <MdCloudDownload />],
    ['md-cloud-done', <MdCloudDone />],
    ['md-insert-chart', <MdInsertChart />],
    ['md-functions', <MdFunctions />],
    ['md-format-quote', <MdFormatQuote />],
    ['md-attach-file', <MdAttachFile />],
    ['md-storage', <MdStorage />],
    ['md-save', <MdSave />],
    ['md-remove-circle-outline', <MdRemoveCircleOutline />],
    ['md-remove-circle', <MdRemoveCircle />],
    ['md-remove', <MdRemove />],
    ['md-low-priority', <MdLowPriority />],
    ['md-link', <MdLink />],
    ['md-gesture', <MdGesture />],
    ['md-forward', <MdForward />],
    ['md-flag', <MdFlag />],
    ['md-drafts', <MdDrafts />],
    ['md-create', <MdCreate />],
    ['md-content-paste', <MdContentPaste />],
    ['md-content-cut', <MdContentCut />],
    ['md-content-copy', <MdContentCopy />],
    ['md-clear', <MdClear />],
    ['md-block', <MdBlock />],
    ['md-backspace', <MdBackspace />],
    ['md-add-box', <MdAddBox />],
    ['md-add', <MdAdd />],
    ['md-add-circle-outline', <MdAddCircleOutline />],
    ['md-add-circle', <MdAddCircle />],
    ['md-location-on', <MdLocationOn />],
    ['md-mail-outline', <MdMailOutline />],
    ['md-email', <MdEmail />],
    ['md-not-interested', <MdNotInterested />],
    ['md-library-books', <MdLibraryBooks />],
    ['md-library-add', <MdLibraryAdd />],
    ['md-equalizer', <MdEqualizer />],
    ['md-add-alert', <MdAddAlert />],
    ['md-visibility-off', <MdVisibilityOff />],
    ['md-visibility', <MdVisibility />],
    ['md-verified-user', <MdVerifiedUser />],
    ['md-update', <MdUpdate />],
    ['md-trending-up', <MdTrendingUp />],
    ['md-trending-flat', <MdTrendingFlat />],
    ['md-trending-down', <MdTrendingDown />],
    ['md-translate', <MdTranslate />],
    ['md-toc', <MdToc />],
    ['md-timeline', <MdTimeline />],
    ['md-thumb-up', <MdThumbUp />],
    ['md-thumb-down', <MdThumbDown />],
    ['md-swap-vert', <MdSwapVert />],
    ['md-swap-horiz', <MdSwapHoriz />],
    ['md-supervisor-account', <MdSupervisorAccount />],
    ['md-subject', <MdSubject />],
    ['md-settings', <MdSettings />],
    ['md-search', <MdSearch />],
    ['md-schedule', <MdSchedule />],
    ['md-restore', <MdRestore />],
    ['md-query-builder', <MdQueryBuilder />],
    ['md-power-settings-new', <MdPowerSettingsNew />],
    ['md-opacity', <MdOpacity />],
    ['md-note-add', <MdNoteAdd />],
    ['md-lock-outline', <MdLockOutline />],
    ['md-lock-open', <MdLockOpen />],
    ['md-list', <MdList />],
    ['md-lightbulb-outline', <MdLightbulbOutline />],
    ['md-launch', <MdLaunch />],
    ['md-label-outline', <MdLabelOutline />],
    ['md-label', <MdLabel />],
    ['md-input', <MdInput />],
    ['md-info-outline', <MdInfoOutline />],
    ['md-info', <MdInfo />],
    ['md-hourglass', <MdHourglassEmpty />],
    ['md-home', <MdHome />],
    ['md-history', <MdHistory />],
    ['md-highlight-off', <MdHighlightOff />],
    ['md-help-outline', <MdHelpOutline />],
    ['md-help', <MdHelp />],
    ['md-get-app', <MdGetApp />],
    ['md-translate', <MdGTranslate />],
    ['md-fingerprint', <MdFingerprint />],
    ['md-findIn-page', <MdFindInPage />],
    ['md-favorite-border', <MdFavoriteBorder />],
    ['md-favorite', <MdFavorite />],
    ['md-extension', <MdExtension />],
    ['md-explore', <MdExplore />],
    ['md-exit-to-app', <MdExitToApp />],
    ['md-event', <MdEvent />],
    ['md-description', <MdDescription />],
    ['md-delete-forever', <MdDeleteForever />],
    ['md-delete', <MdDelete />],
    ['md-dashboard', <MdDashboard />],
    ['md-code', <MdCode />],
    ['md-build', <MdBuild />],
    ['md-bug-report', <MdBugReport />],
    ['md-assignment', <MdAssignment />],
    ['md-assessment', <MdAssessment />],
    ['md-alarm-on', <MdAlarmOn />],
    ['md-alarm-off', <MdAlarmOff />],
    ['md-alarm-add', <MdAlarmAdd />],
    ['md-alarm', <MdAlarm />],
    ['md-account-circle', <MdAccountCircle />],
    ['fc-vlc', <FcVlc />],
    ['fc-view-details', <FcViewDetails />],
    ['fc-upload', <FcUpload />],
    ['fc-tree-structure', <FcTreeStructure />],
    ['fc-timeline', <FcTimeline />],
    ['fc-template', <FcTemplate />],
    ['fc-survey', <FcSurvey />],
    ['fc-signature', <FcSignature />],
    ['fc-share', <FcShare />],
    ['fc-services', <FcServices />],
    ['fc-rules', <FcRules />],
    ['fc-questions', <FcQuestions />],
    ['fc-process', <FcProcess />],
    ['fc-plus', <FcPlus />],
    ['fc-overtime', <FcOvertime />],
    ['fc-organization', <FcOrganization />],
    ['fc-numerical-sorting21', <FcNumericalSorting21 />],
    ['fc-numerical-sorting12', <FcNumericalSorting12 />],
    ['fc-multiple-inputs', <FcMultipleInputs />],
    ['fc-mind-map', <FcMindMap />],
    ['fc-menu', <FcMenu />],
    ['fc-list', <FcList />],
    ['fc-like', <FcLike />],
    ['fc-like-placeholder', <FcLikePlaceholder />],
    ['fc-info', <FcInfo />],
    ['fc-import', <FcImport />],
    ['fc-image-file', <FcImageFile />],
    ['fc-idea', <FcIdea />],
    ['fc-home', <FcHome />],
    ['fc-high-priority', <FcHighPriority />],
    ['fc-low-priority', <FcLowPriority />],
    ['fc-genealogy', <FcGenealogy />],
    ['fc-full-trash', <FcFullTrash />],
    ['fc-document-search', <FcFinePrint />],
    ['fc-file', <FcFile />],
    ['fc-faq', <FcFaq />],
    ['fc-export', <FcExport />],
    ['fc-empty-trash', <FcEmptyTrash />],
    ['fc-download', <FcDownload />],
    ['fc-document', <FcDocument />],
    ['fc-deployment', <FcDeployment />],
    ['fc-delete-database', <FcDeleteDatabase />],
    ['fc-conference-call', <FcConferenceCall />],
    ['fc-database', <FcDatabase />],
    ['fc-data-protection', <FcDataProtection />],
    ['fc-data-encryption', <FcDataEncryption />],
    ['fc-data-configuration', <FcDataConfiguration />],
    ['fc-data-backup', <FcDataBackup />],
    ['fc-checkmark', <FcCheckmark />],
    ['fc-cancel', <FcCancel />],
    ['fc-briefcase', <FcBriefcase />],
    ['fc-binoculars', <FcBinoculars />],
    ['fc-automatic', <FcAutomatic />],
    ['fc-alphabetical-sorting-za', <FcAlphabeticalSortingZa />],
    ['fc-alphabetical-sorting-az', <FcAlphabeticalSortingAz />],
    ['fc-add-database', <FcAddDatabase />],
    ['fc-accept-database', <FcAcceptDatabase />],
    ['fc-about', <FcAbout />],
    ['fc-radar-chart', <FcRadarPlot />],
    ['fc-scatter-chart', <FcScatterPlot />],
    ['fc-pie-chart', <FcPieChart />],
    ['fc-line-chart', <FcLineChart />],
    ['fc-flow-chart', <FcFlowChart />],
    ['fc-doughnut-chart', <FcDoughnutChart />],
    ['fc-bar-chart', <FcBarChart />],
    ['fc-area-chart', <FcAreaChart />],
    ['fc-line-bar-chart', <FcComboChart />],
    ['fc-workflow', <FcWorkflow />],
    ['fc-todo-list', <FcTodoList />],
    ['fc-synchronize', <FcSynchronize />],
    ['fc-repair', <FcSupport />],
    ['fc-statistics', <FcStatistics />],
    ['fc-settings', <FcSettings />],
    ['fc-search', <FcSearch />],
    ['fc-serial-tasks', <FcSerialTasks />],
    ['fc-safe', <FcSafe />],
    ['fc-negative-dynamic', <FcNegativeDynamic />],
    ['fc-positive-dynamic', <FcPositiveDynamic />],
    ['fc-planner', <FcPlanner />],
    ['fc-parallel-tasks', <FcParallelTasks />],
    ['fc-org-unit', <FcOrgUnit />],
    ['fc-opened-folder', <FcOpenedFolder />],
    ['fc-ok', <FcOk />],
    ['fc-inspection', <FcInspection />],
    ['fc-globe', <FcGlobe />],
    ['fc-folder', <FcFolder />],
    ['fc-electronics', <FcElectronics />],
    ['fc-data-sheet', <FcDataSheet />],
    ['fc-command-line', <FcCommandLine />],
    ['fc-calendar', <FcCalendar />],
    ['fc-calculator', <FcCalculator />],
    ['fc-bullish', <FcBullish />],
    ['fc-bearish', <FcBearish />],
    ['fc-bookmark', <FcBookmark />],
    ['fc-approval', <FcApproval />],
    ['fc-advertising', <FcAdvertising />],
    ['di-linux', <DiLinux />],
    ['di-python', <DiPython />],
    ['bi-table', <BiTable />],
    ['bi-analyse', <BiAnalyse />],
    ['bs-list-task', <BsListTask />],
    ['bs-list-check', <BsListCheck />],
    ['bs-link', <BsLink />],
    ['bs-link-45-deg', <BsLink45Deg />],
    ['bs-envelope-open', <BsEnvelopeOpen />],
    ['bs-envelope', <BsEnvelope />],
    ['bs-alarm', <BsAlarm />],
    ['user', <UserOutlined />],
    ['unlock', <UnlockOutlined />],
    ['repair', <ToolOutlined />],
    ['team', <TeamOutlined />],
    ['sync', <SyncOutlined />],
    ['setting', <SettingOutlined />],
    ['send', <SendOutlined />],
    ['schedule', <ScheduleOutlined />],
    ['save', <SaveOutlined />],
    ['rocket', <RocketOutlined />],
    ['reload', <ReloadOutlined />],
    ['read', <ReadOutlined />],
    ['qrcode', <QrcodeOutlined />],
    ['power-off', <PoweroffOutlined />],
    ['number', <NumberOutlined />],
    ['notification', <NotificationOutlined />],
    ['menu', <MenuOutlined />],
    ['mail', <MailOutlined />],
    ['lock', <LockOutlined />],
    ['loading', <LoadingOutlined />],
    ['key', <KeyOutlined />],
    ['hourglass', <HourglassOutlined />],
    ['global', <GlobalOutlined />],
    ['function', <FunctionOutlined />],
    ['import', <ImportOutlined />],
    ['export', <ExportOutlined />],
    ['dashboard', <DashboardOutlined />],
    ['control', <ControlOutlined />],
    ['console-sql', <ConsoleSqlOutlined />],
    ['compass', <CompassOutlined />],
    ['comment', <CommentOutlined />],
    ['code', <CodeOutlined />],
    ['cluster', <ClusterOutlined />],
    ['clear', <ClearOutlined />],
    ['camera', <CameraOutlined />],
    ['book', <BookOutlined />],
    ['catalog', <BarsOutlined />],
    ['api', <ApiOutlined />],
    ['alert', <AlertOutlined />],
    ['account-book', <AccountBookOutlined />],
    ['alipay', <AlipayOutlined />],
    ['alipay-circle', <AlipayCircleOutlined />],
    ['weibo', <WeiboCircleOutlined />],
    ['github', <GithubOutlined />],
    ['fall', <FallOutlined />],
    ['rise', <RiseOutlined />],
    ['stock', <StockOutlined />],
    ['home', <HomeOutlined />],
    ['area-chart', <AreaChartOutlined />],
    ['bar-chart', <BarChartOutlined />],
    ['pie-chart', <PieChartOutlined />],
    ['box-plot', <BoxPlotOutlined />],
    ['dot-chart', <DotChartOutlined />],
    ['line-chart', <LineChartOutlined />],
    ['apartment', <ApartmentOutlined />],
    ['app-store', <AppstoreOutlined />],
    ['app-store-add', <AppstoreAddOutlined />],
    ['bell', <BellOutlined />],
    ['calculator', <CalculatorOutlined />],
    ['calendar', <CalendarOutlined />],
    ['database', <DatabaseOutlined />],
    ['history', <HistoryOutlined />],
    ['search', <SearchOutlined />],
    ['file-search', <FileSearchOutlined />],
    ['cloud', <CloudOutlined />],
    ['cloud-upload', <CloudUploadOutlined />],
    ['cloud-download', <CloudDownloadOutlined />],
    ['cloud-server', <CloudServerOutlined />],
    ['swap', <SwapOutlined />],
    ['im-earth', <ImEarth />],
    ['gi-mesh-network', <GiMeshNetwork style={{ zoom: 1.2 }} />],
    ['rollback', <RollbackOutlined />],
    ['login', <LoginOutlined />],
    ['logout', <LogoutOutlined />],
    ['menu-fold', <MenuFoldOutlined />],
    ['menu-unfold', <MenuUnfoldOutlined />],
    ['full-screen', <FullscreenOutlined />],
    ['full-screen-exit', <FullscreenExitOutlined />],
    ['question-circle', <QuestionCircleOutlined />],
    ['plus-circle', <PlusCircleOutlined />],
    ['minus-circle', <MinusCircleOutlined />],
    ['info-circle', <InfoCircleOutlined />],
    ['exclamation-circle', <ExclamationCircleOutlined />],
    ['close-circle', <CloseCircleOutlined />],
    ['check-circle', <CheckCircleOutlined />],
    ['clock-circle', <ClockCircleOutlined />],
    ['stop', <StopOutlined />],
    ['edit', <EditOutlined />],
    ['delete', <DeleteOutlined />],
    ['highlight', <HighlightOutlined />],
    ['redo', <RedoOutlined />],
    ['undo', <UndoOutlined />],
    ['zoom-in', <ZoomInOutlined />],
    ['zoom-out', <ZoomOutOutlined />],
    ['sort-ascending', <SortAscendingOutlined />],
    ['sort-descending', <SortDescendingOutlined />],
    ['table', <TableOutlined />]
])

export { str2Icon }